version: '3.9'

services:
  frontend:
    build:
      context: ../../../frontend
      dockerfile: Dockerfile
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    env_file:
      -  ../envs/common-frontend.env
